### ISSUE TITLE
Bad Block on syncing testnet 

### ISSUE THREAD

**Issue by APshenkin** [XinFinOrg/XDPoSChain#148]
```
ERROR[12-02|19:23:44]
########## BAD BLOCK #########
Chain config: {ChainID: 51 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: XDPoS}
Number: 23779191
Hash: 0x579ed749b0f8dd60f9f9aa278867a8ed88ca45eeb466353cd6d5060d42e7c10d
	receipt{status=1 cgas=25352 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
Error: invalid gas used (remote: 0 local: 25352)
##############################
```

**Comment by APshenkin** [comment]
In explorer I can see that there is one transaction in this block
https://explorer.apothem.network/blocks/23779191

https://explorer.apothem.network/txs/0x94db31ab04fd7589c6db39cba72b1b73791bfe9bcbadc5f20e98cdcd4b9de28b

but in explorer this transaction appear in other block too
https://explorer.apothem.network/blocks/23779201

**Comment by AnilChinchawale** [comment]
Can you share commit hash that you are using for sync Apothem.

**Comment by APshenkin** [comment]
@AnilChinchawale First I tried to sync it with `f9fa3a8a0711dddeec4559a885a8e8bd992f4791`

But after receiving this error I switched it to `10d9c1d509d59df768aa27a475b281edd3660d01`

**Comment by AnilChinchawale** [comment]
We have fixed the above issue in the latest release v1.4.4 on apothem network.

**Comment by APshenkin** [comment]
@AnilChinchawale Problem is not fixed. Issues still exist for testnet launch

Tried to Sync node with node builded with this commit 
https://github.com/XinFinOrg/XDPoSChain/commit/69cadcc585cf3701991ca456b67a97e7885034b8

```
ERROR[05-20|08:30:51]
########## BAD BLOCK #########
Chain config: {ChainID: 51 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: XDPoS}
Number: 23779191
Hash: 0x579ed749b0f8dd60f9f9aa278867a8ed88ca45eeb466353cd6d5060d42e7c10d
	receipt{status=1 cgas=25352 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
Error: invalid gas used (remote: 0 local: 25352)
##############################
```

**Comment by AnilChinchawale** [comment]
Hello @APshenkin ,

Can you share the startup script and complete logs to review the issue?

For apothem.network we have created new branch **apothem**, Can you try and share logs here.

https://github.com/xinfinorg/XDPoSChain/tree/apothem

**Comment by APshenkin** [comment]
This make sense. Will try and notify you about results

**Comment by APshenkin** [comment]
Works like a charm now. Thanks!

**Comment by AnilChinchawale** [comment]
Great , Thank you👍

In future we will add flag for apothem test, for e.g. —apothem or —testnet
